name: Process Usage Statistics

on:
  issues:
    types: [opened]

jobs:
  process-stats:
    if: contains(github.event.issue.title, 'Usage Stats:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Process statistics
        run: |
          python .github/scripts/process_stats.py
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
